// SPDX-FileCopyrightText: 2023 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AddonsInitParameters struct {

	// If this parameter is left empty, no configurations are required.
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// It specifies whether to disable automatic installation.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// This parameter specifies the name of the component.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// It specifies the version of the component.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AddonsObservation struct {

	// If this parameter is left empty, no configurations are required.
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// It specifies whether to disable automatic installation.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// This parameter specifies the name of the component.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// It specifies the version of the component.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type AddonsParameters struct {

	// If this parameter is left empty, no configurations are required.
	// +kubebuilder:validation:Optional
	Config *string `json:"config,omitempty" tf:"config,omitempty"`

	// It specifies whether to disable automatic installation.
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// This parameter specifies the name of the component.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// It specifies the version of the component.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type MaintenanceWindowInitParameters struct {

	// The maintenance time, values range from 1 to 24,unit is hour. For example: "3h".
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// Whether to open the maintenance window. The following parameters take effect only enable = true.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// Initial maintenance time, For example:"03:00:00Z".
	MaintenanceTime *string `json:"maintenanceTime,omitempty" tf:"maintenance_time,omitempty"`

	// Maintenance cycle, you can set the values from Monday to Sunday, separated by commas when the values are multiple. The default is Thursday.
	WeeklyPeriod *string `json:"weeklyPeriod,omitempty" tf:"weekly_period,omitempty"`
}

type MaintenanceWindowObservation struct {

	// The maintenance time, values range from 1 to 24,unit is hour. For example: "3h".
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// Whether to open the maintenance window. The following parameters take effect only enable = true.
	Enable *bool `json:"enable,omitempty" tf:"enable,omitempty"`

	// Initial maintenance time, For example:"03:00:00Z".
	MaintenanceTime *string `json:"maintenanceTime,omitempty" tf:"maintenance_time,omitempty"`

	// Maintenance cycle, you can set the values from Monday to Sunday, separated by commas when the values are multiple. The default is Thursday.
	WeeklyPeriod *string `json:"weeklyPeriod,omitempty" tf:"weekly_period,omitempty"`
}

type MaintenanceWindowParameters struct {

	// The maintenance time, values range from 1 to 24,unit is hour. For example: "3h".
	// +kubebuilder:validation:Optional
	Duration *string `json:"duration" tf:"duration,omitempty"`

	// Whether to open the maintenance window. The following parameters take effect only enable = true.
	// +kubebuilder:validation:Optional
	Enable *bool `json:"enable" tf:"enable,omitempty"`

	// Initial maintenance time, For example:"03:00:00Z".
	// +kubebuilder:validation:Optional
	MaintenanceTime *string `json:"maintenanceTime" tf:"maintenance_time,omitempty"`

	// Maintenance cycle, you can set the values from Monday to Sunday, separated by commas when the values are multiple. The default is Thursday.
	// +kubebuilder:validation:Optional
	WeeklyPeriod *string `json:"weeklyPeriod" tf:"weekly_period,omitempty"`
}

type ManagedKubernetesInitParameters struct {

	// A list of API audiences for Service Account Token Volume Projection. Set this to ["https://kubernetes.default.svc"] if you want to enable the Token Volume Projection feature (requires specifying service_account_issuer as well. From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	APIAudiences []*string `json:"apiAudiences,omitempty" tf:"api_audiences,omitempty"`

	// The addon you want to install in cluster. See addons below.
	Addons []AddonsInitParameters `json:"addons,omitempty" tf:"addons,omitempty"`

	// The path of client certificate, like ~/.kube/client-cert.pem.
	ClientCert *string `json:"clientCert,omitempty" tf:"client_cert,omitempty"`

	// The path of client key, like ~/.kube/client-key.pem.
	ClientKey *string `json:"clientKey,omitempty" tf:"client_key,omitempty"`

	// The path of cluster ca certificate, like ~/.kube/cluster-ca-cert.pem
	ClusterCACert *string `json:"clusterCaCert,omitempty" tf:"cluster_ca_cert,omitempty"`

	// Cluster local domain name, Default to cluster.local. A domain name consists of one or more sections separated by a decimal point (.), each of which is up to 63 characters long, and can be lowercase, numerals, and underscores (-), and must be lowercase or numerals at the beginning and end.
	// cluster local domain
	ClusterDomain *string `json:"clusterDomain,omitempty" tf:"cluster_domain,omitempty"`

	// The cluster specifications of kubernetes cluster,which can be empty. Valid values:
	ClusterSpec *string `json:"clusterSpec,omitempty" tf:"cluster_spec,omitempty"`

	// List of target components for which logs need to be collected. Supports apiserver, kcm, scheduler, ccm and controlplane-events.
	ControlPlaneLogComponents []*string `json:"controlPlaneLogComponents,omitempty" tf:"control_plane_log_components,omitempty"`

	// Control plane log project. If this field is not set, a log service project named k8s-log-{ClusterID} will be automatically created.
	ControlPlaneLogProject *string `json:"controlPlaneLogProject,omitempty" tf:"control_plane_log_project,omitempty"`

	// Control plane log retention duration (unit: day). Default 30. If control plane logs are to be collected, control_plane_log_ttl and control_plane_log_components must be specified.
	ControlPlaneLogTTL *string `json:"controlPlaneLogTtl,omitempty" tf:"control_plane_log_ttl,omitempty"`

	// Customize the certificate SAN, multiple IP or domain names are separated by English commas (,).
	CustomSan *string `json:"customSan,omitempty" tf:"custom_san,omitempty"`

	// Whether to enable cluster deletion protection.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Whether to enable cluster to support RRSA for version 1.22.3+. Default to false. Once the RRSA function is turned on, it is not allowed to turn off. If your cluster has enabled this function, please manually modify your tf file and add the rrsa configuration to the file, learn more RAM Roles for Service Accounts.
	EnableRrsa *bool `json:"enableRrsa,omitempty" tf:"enable_rrsa,omitempty"`

	// The disk encryption key.
	// disk encryption key, only in ack-pro
	EncryptionProviderKey *string `json:"encryptionProviderKey,omitempty" tf:"encryption_provider_key,omitempty"`

	// Enable to create advanced security group. default: false. See Advanced security group.
	IsEnterpriseSecurityGroup *bool `json:"isEnterpriseSecurityGroup,omitempty" tf:"is_enterprise_security_group,omitempty"`

	// The cluster api server load balance instance specification, default slb.s1.small. For more information on how to select a LB instance specification, see SLB instance overview.
	LoadBalancerSpec *string `json:"loadBalancerSpec,omitempty" tf:"load_balancer_spec,omitempty"`

	// The cluster maintenance window，effective only in the professional managed cluster. Managed node pool will use it. See maintenance_window below.
	MaintenanceWindow []MaintenanceWindowInitParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// The kubernetes cluster's name. It is unique in one Alicloud account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether to create a new nat gateway while creating kubernetes cluster. Default to true. Then openapi in Alibaba Cloud are not all on intranet, So turn this option on is a good choice.
	NewNATGateway *bool `json:"newNatGateway,omitempty" tf:"new_nat_gateway,omitempty"`

	// The node cidr block to specific how many pods can run on single node. 24-28 is allowed. 24 means 2^(32-24)-1=255 and the node can run at most 255 pods. default: 24
	NodeCidrMask *float64 `json:"nodeCidrMask,omitempty" tf:"node_cidr_mask,omitempty"`

	// - [Flannel Specific] The CIDR block for the pod network when using Flannel.
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// - [Terway Specific] The vswitches for the pod network when using Terway.Be careful the pod_vswitch_ids can not equal to worker_vswitch_ids or master_vswitch_ids but must be in same availability zones.
	PodVswitchIds []*string `json:"podVswitchIds,omitempty" tf:"pod_vswitch_ids,omitempty"`

	// Proxy mode is option of kube-proxy. options: iptables|ipvs. default: ipvs.
	ProxyMode *string `json:"proxyMode,omitempty" tf:"proxy_mode,omitempty"`

	// The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Resources that are automatically created during cluster creation, including NAT gateways, SNAT rules, SLB instances, and RAM Role, will be deleted. Resources that are manually created after you create the cluster, such as SLB instances for Services, will also be deleted. If you need to retain resources, please configure with retain_resources. There are several aspects to pay attention to when using retain_resources to retain resources.
	RetainResources []*string `json:"retainResources,omitempty" tf:"retain_resources,omitempty"`

	// The ID of the security group to which the ECS instances in the cluster belong. If it is not specified, a new Security group will be built.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// The issuer of the Service Account token for Service Account Token Volume Projection, corresponds to the iss field in the token payload. Set this to "https://kubernetes.default.svc" to enable the Token Volume Projection feature (requires specifying api_audiences as well). From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	ServiceAccountIssuer *string `json:"serviceAccountIssuer,omitempty" tf:"service_account_issuer,omitempty"`

	// The CIDR block for the service network. It cannot be duplicated with the VPC CIDR and CIDR used by Kubernetes cluster in VPC, cannot be modified after creation.
	ServiceCidr *string `json:"serviceCidr,omitempty" tf:"service_cidr,omitempty"`

	// Whether to create internet load balancer for API Server. Default to true.
	SlbInternetEnabled *bool `json:"slbInternetEnabled,omitempty" tf:"slb_internet_enabled,omitempty"`

	// Default nil, A map of tags assigned to the kubernetes cluster and work nodes. See tags below.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// When you create a cluster, set the time zones for the Master and Worker nodes. You can only change the managed node time zone if you create a cluster. Once the cluster is created, you can only change the time zone of the Worker node.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The path of customized CA cert, you can use this CA to sign client certs to connect your cluster.
	UserCA *string `json:"userCa,omitempty" tf:"user_ca,omitempty"`

	// Desired Kubernetes version. If you do not specify a value, the latest available version at resource creation is used and no upgrades will occur except you set a higher version number. The value must be configured and increased to upgrade the version when desired. Downgrades are not supported by ACK.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// The vswitches used by control plane.  See worker_vswitch_ids below.
	WorkerVswitchIds []*string `json:"workerVswitchIds,omitempty" tf:"worker_vswitch_ids,omitempty"`
}

type ManagedKubernetesObservation struct {

	// A list of API audiences for Service Account Token Volume Projection. Set this to ["https://kubernetes.default.svc"] if you want to enable the Token Volume Projection feature (requires specifying service_account_issuer as well. From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	APIAudiences []*string `json:"apiAudiences,omitempty" tf:"api_audiences,omitempty"`

	// The addon you want to install in cluster. See addons below.
	Addons []AddonsObservation `json:"addons,omitempty" tf:"addons,omitempty"`

	// (Available in 1.105.0+) Nested attribute containing certificate authority data for your cluster.
	// +mapType=granular
	CertificateAuthority map[string]*string `json:"certificateAuthority,omitempty" tf:"certificate_authority,omitempty"`

	// The path of client certificate, like ~/.kube/client-cert.pem.
	ClientCert *string `json:"clientCert,omitempty" tf:"client_cert,omitempty"`

	// The path of client key, like ~/.kube/client-key.pem.
	ClientKey *string `json:"clientKey,omitempty" tf:"client_key,omitempty"`

	// The path of cluster ca certificate, like ~/.kube/cluster-ca-cert.pem
	ClusterCACert *string `json:"clusterCaCert,omitempty" tf:"cluster_ca_cert,omitempty"`

	// Cluster local domain name, Default to cluster.local. A domain name consists of one or more sections separated by a decimal point (.), each of which is up to 63 characters long, and can be lowercase, numerals, and underscores (-), and must be lowercase or numerals at the beginning and end.
	// cluster local domain
	ClusterDomain *string `json:"clusterDomain,omitempty" tf:"cluster_domain,omitempty"`

	// The cluster specifications of kubernetes cluster,which can be empty. Valid values:
	ClusterSpec *string `json:"clusterSpec,omitempty" tf:"cluster_spec,omitempty"`

	// Map of kubernetes cluster connection information.
	// +mapType=granular
	Connections map[string]*string `json:"connections,omitempty" tf:"connections,omitempty"`

	// List of target components for which logs need to be collected. Supports apiserver, kcm, scheduler, ccm and controlplane-events.
	ControlPlaneLogComponents []*string `json:"controlPlaneLogComponents,omitempty" tf:"control_plane_log_components,omitempty"`

	// Control plane log project. If this field is not set, a log service project named k8s-log-{ClusterID} will be automatically created.
	ControlPlaneLogProject *string `json:"controlPlaneLogProject,omitempty" tf:"control_plane_log_project,omitempty"`

	// Control plane log retention duration (unit: day). Default 30. If control plane logs are to be collected, control_plane_log_ttl and control_plane_log_components must be specified.
	ControlPlaneLogTTL *string `json:"controlPlaneLogTtl,omitempty" tf:"control_plane_log_ttl,omitempty"`

	// Customize the certificate SAN, multiple IP or domain names are separated by English commas (,).
	CustomSan *string `json:"customSan,omitempty" tf:"custom_san,omitempty"`

	// Whether to enable cluster deletion protection.
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Whether to enable cluster to support RRSA for version 1.22.3+. Default to false. Once the RRSA function is turned on, it is not allowed to turn off. If your cluster has enabled this function, please manually modify your tf file and add the rrsa configuration to the file, learn more RAM Roles for Service Accounts.
	EnableRrsa *bool `json:"enableRrsa,omitempty" tf:"enable_rrsa,omitempty"`

	// The disk encryption key.
	// disk encryption key, only in ack-pro
	EncryptionProviderKey *string `json:"encryptionProviderKey,omitempty" tf:"encryption_provider_key,omitempty"`

	// The ID of the container cluster.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Enable to create advanced security group. default: false. See Advanced security group.
	IsEnterpriseSecurityGroup *bool `json:"isEnterpriseSecurityGroup,omitempty" tf:"is_enterprise_security_group,omitempty"`

	// The cluster api server load balance instance specification, default slb.s1.small. For more information on how to select a LB instance specification, see SLB instance overview.
	LoadBalancerSpec *string `json:"loadBalancerSpec,omitempty" tf:"load_balancer_spec,omitempty"`

	// The cluster maintenance window，effective only in the professional managed cluster. Managed node pool will use it. See maintenance_window below.
	MaintenanceWindow []MaintenanceWindowObservation `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// The ID of nat gateway used to launch kubernetes cluster.
	NATGatewayID *string `json:"natGatewayId,omitempty" tf:"nat_gateway_id,omitempty"`

	// The kubernetes cluster's name. It is unique in one Alicloud account.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether to create a new nat gateway while creating kubernetes cluster. Default to true. Then openapi in Alibaba Cloud are not all on intranet, So turn this option on is a good choice.
	NewNATGateway *bool `json:"newNatGateway,omitempty" tf:"new_nat_gateway,omitempty"`

	// The node cidr block to specific how many pods can run on single node. 24-28 is allowed. 24 means 2^(32-24)-1=255 and the node can run at most 255 pods. default: 24
	NodeCidrMask *float64 `json:"nodeCidrMask,omitempty" tf:"node_cidr_mask,omitempty"`

	// - [Flannel Specific] The CIDR block for the pod network when using Flannel.
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// - [Terway Specific] The vswitches for the pod network when using Terway.Be careful the pod_vswitch_ids can not equal to worker_vswitch_ids or master_vswitch_ids but must be in same availability zones.
	PodVswitchIds []*string `json:"podVswitchIds,omitempty" tf:"pod_vswitch_ids,omitempty"`

	// Proxy mode is option of kube-proxy. options: iptables|ipvs. default: ipvs.
	ProxyMode *string `json:"proxyMode,omitempty" tf:"proxy_mode,omitempty"`

	// The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Resources that are automatically created during cluster creation, including NAT gateways, SNAT rules, SLB instances, and RAM Role, will be deleted. Resources that are manually created after you create the cluster, such as SLB instances for Services, will also be deleted. If you need to retain resources, please configure with retain_resources. There are several aspects to pay attention to when using retain_resources to retain resources.
	RetainResources []*string `json:"retainResources,omitempty" tf:"retain_resources,omitempty"`

	// Nested attribute containing RRSA related data for your cluster.
	RrsaMetadata []RrsaMetadataObservation `json:"rrsaMetadata,omitempty" tf:"rrsa_metadata,omitempty"`

	// The ID of the security group to which the ECS instances in the cluster belong. If it is not specified, a new Security group will be built.
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// The issuer of the Service Account token for Service Account Token Volume Projection, corresponds to the iss field in the token payload. Set this to "https://kubernetes.default.svc" to enable the Token Volume Projection feature (requires specifying api_audiences as well). From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	ServiceAccountIssuer *string `json:"serviceAccountIssuer,omitempty" tf:"service_account_issuer,omitempty"`

	// The CIDR block for the service network. It cannot be duplicated with the VPC CIDR and CIDR used by Kubernetes cluster in VPC, cannot be modified after creation.
	ServiceCidr *string `json:"serviceCidr,omitempty" tf:"service_cidr,omitempty"`

	// (Deprecated) The ID of load balancer.
	SlbID *string `json:"slbId,omitempty" tf:"slb_id,omitempty"`

	// The public ip of load balancer.
	SlbInternet *string `json:"slbInternet,omitempty" tf:"slb_internet,omitempty"`

	// Whether to create internet load balancer for API Server. Default to true.
	SlbInternetEnabled *bool `json:"slbInternetEnabled,omitempty" tf:"slb_internet_enabled,omitempty"`

	// The ID of private load balancer where the current cluster master node is located.
	SlbIntranet *string `json:"slbIntranet,omitempty" tf:"slb_intranet,omitempty"`

	// Default nil, A map of tags assigned to the kubernetes cluster and work nodes. See tags below.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// When you create a cluster, set the time zones for the Master and Worker nodes. You can only change the managed node time zone if you create a cluster. Once the cluster is created, you can only change the time zone of the Worker node.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The path of customized CA cert, you can use this CA to sign client certs to connect your cluster.
	UserCA *string `json:"userCa,omitempty" tf:"user_ca,omitempty"`

	// The ID of VPC where the current cluster is located.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Desired Kubernetes version. If you do not specify a value, the latest available version at resource creation is used and no upgrades will occur except you set a higher version number. The value must be configured and increased to upgrade the version when desired. Downgrades are not supported by ACK.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// The RamRole Name attached to worker node.
	WorkerRAMRoleName *string `json:"workerRamRoleName,omitempty" tf:"worker_ram_role_name,omitempty"`

	// The vswitches used by control plane.  See worker_vswitch_ids below.
	WorkerVswitchIds []*string `json:"workerVswitchIds,omitempty" tf:"worker_vswitch_ids,omitempty"`
}

type ManagedKubernetesParameters struct {

	// A list of API audiences for Service Account Token Volume Projection. Set this to ["https://kubernetes.default.svc"] if you want to enable the Token Volume Projection feature (requires specifying service_account_issuer as well. From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	// +kubebuilder:validation:Optional
	APIAudiences []*string `json:"apiAudiences,omitempty" tf:"api_audiences,omitempty"`

	// The addon you want to install in cluster. See addons below.
	// +kubebuilder:validation:Optional
	Addons []AddonsParameters `json:"addons,omitempty" tf:"addons,omitempty"`

	// The path of client certificate, like ~/.kube/client-cert.pem.
	// +kubebuilder:validation:Optional
	ClientCert *string `json:"clientCert,omitempty" tf:"client_cert,omitempty"`

	// The path of client key, like ~/.kube/client-key.pem.
	// +kubebuilder:validation:Optional
	ClientKey *string `json:"clientKey,omitempty" tf:"client_key,omitempty"`

	// The path of cluster ca certificate, like ~/.kube/cluster-ca-cert.pem
	// +kubebuilder:validation:Optional
	ClusterCACert *string `json:"clusterCaCert,omitempty" tf:"cluster_ca_cert,omitempty"`

	// Cluster local domain name, Default to cluster.local. A domain name consists of one or more sections separated by a decimal point (.), each of which is up to 63 characters long, and can be lowercase, numerals, and underscores (-), and must be lowercase or numerals at the beginning and end.
	// cluster local domain
	// +kubebuilder:validation:Optional
	ClusterDomain *string `json:"clusterDomain,omitempty" tf:"cluster_domain,omitempty"`

	// The cluster specifications of kubernetes cluster,which can be empty. Valid values:
	// +kubebuilder:validation:Optional
	ClusterSpec *string `json:"clusterSpec,omitempty" tf:"cluster_spec,omitempty"`

	// List of target components for which logs need to be collected. Supports apiserver, kcm, scheduler, ccm and controlplane-events.
	// +kubebuilder:validation:Optional
	ControlPlaneLogComponents []*string `json:"controlPlaneLogComponents,omitempty" tf:"control_plane_log_components,omitempty"`

	// Control plane log project. If this field is not set, a log service project named k8s-log-{ClusterID} will be automatically created.
	// +kubebuilder:validation:Optional
	ControlPlaneLogProject *string `json:"controlPlaneLogProject,omitempty" tf:"control_plane_log_project,omitempty"`

	// Control plane log retention duration (unit: day). Default 30. If control plane logs are to be collected, control_plane_log_ttl and control_plane_log_components must be specified.
	// +kubebuilder:validation:Optional
	ControlPlaneLogTTL *string `json:"controlPlaneLogTtl,omitempty" tf:"control_plane_log_ttl,omitempty"`

	// Customize the certificate SAN, multiple IP or domain names are separated by English commas (,).
	// +kubebuilder:validation:Optional
	CustomSan *string `json:"customSan,omitempty" tf:"custom_san,omitempty"`

	// Whether to enable cluster deletion protection.
	// +kubebuilder:validation:Optional
	DeletionProtection *bool `json:"deletionProtection,omitempty" tf:"deletion_protection,omitempty"`

	// Whether to enable cluster to support RRSA for version 1.22.3+. Default to false. Once the RRSA function is turned on, it is not allowed to turn off. If your cluster has enabled this function, please manually modify your tf file and add the rrsa configuration to the file, learn more RAM Roles for Service Accounts.
	// +kubebuilder:validation:Optional
	EnableRrsa *bool `json:"enableRrsa,omitempty" tf:"enable_rrsa,omitempty"`

	// The disk encryption key.
	// disk encryption key, only in ack-pro
	// +kubebuilder:validation:Optional
	EncryptionProviderKey *string `json:"encryptionProviderKey,omitempty" tf:"encryption_provider_key,omitempty"`

	// Enable to create advanced security group. default: false. See Advanced security group.
	// +kubebuilder:validation:Optional
	IsEnterpriseSecurityGroup *bool `json:"isEnterpriseSecurityGroup,omitempty" tf:"is_enterprise_security_group,omitempty"`

	// The cluster api server load balance instance specification, default slb.s1.small. For more information on how to select a LB instance specification, see SLB instance overview.
	// +kubebuilder:validation:Optional
	LoadBalancerSpec *string `json:"loadBalancerSpec,omitempty" tf:"load_balancer_spec,omitempty"`

	// The cluster maintenance window，effective only in the professional managed cluster. Managed node pool will use it. See maintenance_window below.
	// +kubebuilder:validation:Optional
	MaintenanceWindow []MaintenanceWindowParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// The kubernetes cluster's name. It is unique in one Alicloud account.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether to create a new nat gateway while creating kubernetes cluster. Default to true. Then openapi in Alibaba Cloud are not all on intranet, So turn this option on is a good choice.
	// +kubebuilder:validation:Optional
	NewNATGateway *bool `json:"newNatGateway,omitempty" tf:"new_nat_gateway,omitempty"`

	// The node cidr block to specific how many pods can run on single node. 24-28 is allowed. 24 means 2^(32-24)-1=255 and the node can run at most 255 pods. default: 24
	// +kubebuilder:validation:Optional
	NodeCidrMask *float64 `json:"nodeCidrMask,omitempty" tf:"node_cidr_mask,omitempty"`

	// - [Flannel Specific] The CIDR block for the pod network when using Flannel.
	// +kubebuilder:validation:Optional
	PodCidr *string `json:"podCidr,omitempty" tf:"pod_cidr,omitempty"`

	// - [Terway Specific] The vswitches for the pod network when using Terway.Be careful the pod_vswitch_ids can not equal to worker_vswitch_ids or master_vswitch_ids but must be in same availability zones.
	// +kubebuilder:validation:Optional
	PodVswitchIds []*string `json:"podVswitchIds,omitempty" tf:"pod_vswitch_ids,omitempty"`

	// Proxy mode is option of kube-proxy. options: iptables|ipvs. default: ipvs.
	// +kubebuilder:validation:Optional
	ProxyMode *string `json:"proxyMode,omitempty" tf:"proxy_mode,omitempty"`

	// The ID of the resource group,by default these cloud resources are automatically assigned to the default resource group.
	// +kubebuilder:validation:Optional
	ResourceGroupID *string `json:"resourceGroupId,omitempty" tf:"resource_group_id,omitempty"`

	// Resources that are automatically created during cluster creation, including NAT gateways, SNAT rules, SLB instances, and RAM Role, will be deleted. Resources that are manually created after you create the cluster, such as SLB instances for Services, will also be deleted. If you need to retain resources, please configure with retain_resources. There are several aspects to pay attention to when using retain_resources to retain resources.
	// +kubebuilder:validation:Optional
	RetainResources []*string `json:"retainResources,omitempty" tf:"retain_resources,omitempty"`

	// The ID of the security group to which the ECS instances in the cluster belong. If it is not specified, a new Security group will be built.
	// +kubebuilder:validation:Optional
	SecurityGroupID *string `json:"securityGroupId,omitempty" tf:"security_group_id,omitempty"`

	// The issuer of the Service Account token for Service Account Token Volume Projection, corresponds to the iss field in the token payload. Set this to "https://kubernetes.default.svc" to enable the Token Volume Projection feature (requires specifying api_audiences as well). From cluster version 1.22+, Service Account Token Volume Projection will be enabled by default.
	// +kubebuilder:validation:Optional
	ServiceAccountIssuer *string `json:"serviceAccountIssuer,omitempty" tf:"service_account_issuer,omitempty"`

	// The CIDR block for the service network. It cannot be duplicated with the VPC CIDR and CIDR used by Kubernetes cluster in VPC, cannot be modified after creation.
	// +kubebuilder:validation:Optional
	ServiceCidr *string `json:"serviceCidr,omitempty" tf:"service_cidr,omitempty"`

	// Whether to create internet load balancer for API Server. Default to true.
	// +kubebuilder:validation:Optional
	SlbInternetEnabled *bool `json:"slbInternetEnabled,omitempty" tf:"slb_internet_enabled,omitempty"`

	// Default nil, A map of tags assigned to the kubernetes cluster and work nodes. See tags below.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// When you create a cluster, set the time zones for the Master and Worker nodes. You can only change the managed node time zone if you create a cluster. Once the cluster is created, you can only change the time zone of the Worker node.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// The path of customized CA cert, you can use this CA to sign client certs to connect your cluster.
	// +kubebuilder:validation:Optional
	UserCA *string `json:"userCa,omitempty" tf:"user_ca,omitempty"`

	// Desired Kubernetes version. If you do not specify a value, the latest available version at resource creation is used and no upgrades will occur except you set a higher version number. The value must be configured and increased to upgrade the version when desired. Downgrades are not supported by ACK.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`

	// The vswitches used by control plane.  See worker_vswitch_ids below.
	// +kubebuilder:validation:Optional
	WorkerVswitchIds []*string `json:"workerVswitchIds,omitempty" tf:"worker_vswitch_ids,omitempty"`
}

type RrsaMetadataInitParameters struct {
}

type RrsaMetadataObservation struct {

	// Whether the RRSA feature has been enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The arn of OIDC provider that was registered in RAM.
	RAMOidcProviderArn *string `json:"ramOidcProviderArn,omitempty" tf:"ram_oidc_provider_arn,omitempty"`

	// The name of OIDC Provider that was registered in RAM.
	RAMOidcProviderName *string `json:"ramOidcProviderName,omitempty" tf:"ram_oidc_provider_name,omitempty"`

	// The issuer URL of RRSA OIDC Token.
	RrsaOidcIssuerURL *string `json:"rrsaOidcIssuerUrl,omitempty" tf:"rrsa_oidc_issuer_url,omitempty"`
}

type RrsaMetadataParameters struct {
}

// ManagedKubernetesSpec defines the desired state of ManagedKubernetes
type ManagedKubernetesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManagedKubernetesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagedKubernetesInitParameters `json:"initProvider,omitempty"`
}

// ManagedKubernetesStatus defines the observed state of ManagedKubernetes.
type ManagedKubernetesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagedKubernetesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagedKubernetes is the Schema for the ManagedKubernetess API. Provides a Alicloud resource to manage container managed kubernetes cluster.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,alibabacloud}
type ManagedKubernetes struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.workerVswitchIds) || (has(self.initProvider) && has(self.initProvider.workerVswitchIds))",message="spec.forProvider.workerVswitchIds is a required parameter"
	Spec   ManagedKubernetesSpec   `json:"spec"`
	Status ManagedKubernetesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagedKubernetesList contains a list of ManagedKubernetess
type ManagedKubernetesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagedKubernetes `json:"items"`
}

// Repository type metadata.
var (
	ManagedKubernetes_Kind             = "ManagedKubernetes"
	ManagedKubernetes_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagedKubernetes_Kind}.String()
	ManagedKubernetes_KindAPIVersion   = ManagedKubernetes_Kind + "." + CRDGroupVersion.String()
	ManagedKubernetes_GroupVersionKind = CRDGroupVersion.WithKind(ManagedKubernetes_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagedKubernetes{}, &ManagedKubernetesList{})
}
