# permissions for end users to view aliyunmanagedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: aliyunmanagedcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-aliyun
    app.kubernetes.io/part-of: cluster-api-provider-aliyun
    app.kubernetes.io/managed-by: kustomize
  name: aliyunmanagedcluster-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - aliyunmanagedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - aliyunmanagedclusters/status
  verbs:
  - get
