# The following patch adds a directive for certmanager to inject CA into the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aliyunmanagedcontrolplanes.controlplane.cluster.x-k8s.io
  labels:
    cluster.x-k8s.io/provider: infrastructure-aliyun
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha4
    cluster.x-k8s.io/v1beta1: v1beta1_v1beta2
    clusterctl.cluster.x-k8s.io: ""
spec:
  names:
    shortNames:
    - alicp
