# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/infrastructure.cluster.x-k8s.io_aliyunmanagedclusters.yaml
- bases/controlplane.cluster.x-k8s.io_aliyunmanagedcontrolplanes.yaml
- bases/infrastructure.cluster.x-k8s.io_aliyunmanagedmachinepools.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
##
## "kubebuilder create webhook"生成 webhook 模板时会解开对应 yaml 行的注释
## (为哪个资源创建 webhook, 就解开哪一行)
## 但是会有 bug, 总是只解开第一行(aliyunmanagedclusters这一行), 这样在 make manifests
## 时会报错, 需要手动修改对应的行.
##
#- path: patches/webhook_in_aliyunmanagedclusters.yaml
- path: patches/webhook_in_controlplane_aliyunmanagedcontrolplanes.yaml
- path: patches/webhook_in_infrastructure_aliyunmanagedmachinepools.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_aliyunmanagedclusters.yaml
#- path: patches/cainjection_in_controlplane_aliyunmanagedcontrolplanes.yaml
#- path: patches/cainjection_in_infrastructure_aliyunmanagedmachinepools.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.

## cluster-api 需要在自定义 CRD 中添加指定 label,
## 这样 capi-controller 才能通过 infrastructureRef、controlPlaneRef 找到指定资源.
## 但是这部分内容只在 make deploy 才会生效, make manifests 更新的 config/crd/bases 的
## yaml 中是不会出现的.
- path: patches/capi_in_controlplane_aliyunmanagedcontrolplanes.yaml
- path: patches/capi_in_infrastructure_aliyunmanagedmachinepools.yaml
- path: patches/capi_in_infrastructure_aliyunmanagedclusters.yaml

configurations:
- kustomizeconfig.yaml
